[package]
name = "advent_of_code"
version = "0.8.0"
authors = ["Michael Strobel"]
edition = "2021"
default-run = "advent_of_code"
publish = false

[dependencies]
pico-args = "0.5.0"
itertools = "0.10.5"
regex = "1"
